[package]
name = "advent_of_code_2024"
authors = ["Benjamín Montenegro <benjamin.montenegrom@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
cached = "0.54.0"
nom = "7.1.3"
